docs: add ubuntu docker install
api7/apache-apisix-best-practices pull request #5
Opened 2021-01-03 08:26 UTC by Firstsawyou

ubuntu 安装 APISIX

2021-01-05 14:54 UTC, membphis requested changes

2021-01-05 14:54 UTC, membphis commented on install/ubuntu_docker_install.md
> +如何在 Ubuntu 系统上快速安装并运行 APISIX 服务，本教程将依据 [APISIX 官方文档](https://github.com/apache/apisix/blob/master/README.md)，将带您从零搭建 APISIX 服务。
这里一定要突出 “docker” 关键字

2021-01-05 15:43 UTC, Firstsawyou commented on install/ubuntu_docker_install.md
> +如何在 Ubuntu 系统上快速安装并运行 APISIX 服务，本教程将依据 [APISIX 官方文档](https://github.com/apache/apisix/blob/master/README.md)，将带您从零搭建 APISIX 服务。
已更新

2021-01-06 09:06 UTC, idbeta commented on install/ubuntu_docker_install.md
> +
建议增加`如何进入容器`的方法

2021-01-06 11:15 UTC, Firstsawyou commented on install/ubuntu_docker_install.md
> +
启动和进入一起放在了步骤3，步骤3的名称已改为 `启动及进入容器`。

2021-01-07 07:25 UTC, membphis requested changes

2021-01-07 07:25 UTC, membphis commented on install/ubuntu_docker_install.md
> +# Ubuntu 安装 APISIX
标题也要突出 docker 关键字哈

2021-01-07 07:25 UTC, membphis commented on install/ubuntu_docker_install.md
> +$ docker run -it apache/apisix:latest /bin/bash
docker 的这个启动方法有些诡异

应该是这样的：`docker run -d -p 9080:9080 apache/apisix:latest`

2021-01-07 07:25 UTC, membphis commented on install/ubuntu_docker_install.md
> +4、容器中安装 etcd
容器中安装 etcd ，更诡异了

@Firstsawyou 你使用 docker 的姿势很诡异

2021-01-07 07:34 UTC, Firstsawyou commented on install/ubuntu_docker_install.md
> +4、容器中安装 etcd
嗯，好的。我后面重新整理更新一下

2021-01-11 03:07 UTC, Firstsawyou commented on install/ubuntu_docker_install.md
> +4、容器中安装 etcd
已更新

2021-01-11 05:41 UTC, membphis approved these changes

2021-01-11 05:41 UTC, merged