docs: how to modify the configuration file.
api7/apache-apisix-best-practices pull request #9
Opened 2021-01-05 17:15 UTC by Firstsawyou

close #3

2021-01-06 09:01 UTC, idbeta commented on getting_started/modify_config_file.md
> +
`简绍`->`介绍`

2021-01-06 09:03 UTC, idbeta commented on getting_started/modify_config_file.md
> +APISIX 具有一个默认的配置文件 `config-default.yaml` 和一个自定义的配置文件 `config.yaml` ，它们之间是一种增量的关系。如果两个文件中存在相同字段信息的配置，则是 `config.yaml` 文件中的配置生效。
建议去掉`具有`的`具`

2021-01-06 10:41 UTC, Firstsawyou commented on getting_started/modify_config_file.md
> +
已修复

2021-01-06 10:41 UTC, Firstsawyou commented on getting_started/modify_config_file.md
> +APISIX 具有一个默认的配置文件 `config-default.yaml` 和一个自定义的配置文件 `config.yaml` ，它们之间是一种增量的关系。如果两个文件中存在相同字段信息的配置，则是 `config.yaml` 文件中的配置生效。
已更新

2021-01-07 07:20 UTC, membphis requested changes

2021-01-07 07:20 UTC, membphis commented on getting_started/modify_config_file.md
> +APISIX 有一个默认的配置文件 `config-default.yaml` 和一个自定义的配置文件 `config.yaml` ，它们之间是一种增量的关系。如果两个文件中存在相同字段信息的配置，则是 `config.yaml` 文件中的配置生效。
需要明确提示用户，不需要修改 `config-default.yaml`，任何用户配置都应在 `config.yaml` 设置

2021-01-07 07:20 UTC, membphis commented on getting_started/modify_config_file.md
> +
可以给读者实操一下，比如修改后启动 APISIX 服务，查看一下当前 nginx.conf 生成的配置和 APISIX 服务监听的端口

2021-01-07 07:20 UTC, membphis commented on getting_started/modify_config_file.md
> +  host: "http://foo:2379"       # etcd address
`foo` 不是一个好名字

2021-01-11 03:19 UTC, Firstsawyou commented on getting_started/modify_config_file.md
> +APISIX 有一个默认的配置文件 `config-default.yaml` 和一个自定义的配置文件 `config.yaml` ，它们之间是一种增量的关系。如果两个文件中存在相同字段信息的配置，则是 `config.yaml` 文件中的配置生效。
已更新

2021-01-11 03:19 UTC, Firstsawyou commented on getting_started/modify_config_file.md
> +
updated.

2021-01-11 05:52 UTC, membphis approved these changes

2021-01-11 05:53 UTC, merged